NeoSans.png:
    derived-from: grafx2-fonts

day_night_cycle_gradient.png:
    derived-from: nilsson-lpc-entry

day_night_pixels.*:
    author: Stuart Pernsteiner
    attribution: >
        Casper Nilsson's day/night cycle gradient, adjusted to make it more
        suitable for multiplying rather than alpha blending, and to make the
        nights darker.

