
-lpc-base: &lpc-base
    derived-from: lpc-base-tiles

-nilsson-lpc: &nilsson-lpc
    derived-from: nilsson-lpc-entry

-gervais-roguelike: &gervais-roguelike
    derived-from: gervais-roguelike-tiles

-daneeklu-farming: &daneeklu-farming
    derived-from: daneeklu-farming-tilesets


barrel.png: *lpc-base
cave-junk.png: *lpc-base
chest.png: *lpc-base
furniture.png: *lpc-base
furniture.xcf: *lpc-base
furniture-planemap.png: *lpc-base
rock.png: *lpc-base
stair.png: *lpc-base
stair-planemap.png: *lpc-base
trophy.png: *lpc-base
wood-floor.png: *lpc-base

road.png: *nilsson-lpc

crystal-formation.png: *gervais-roguelike
crystal-formation-red.png: *gervais-roguelike
crystal-formation-green.png: *gervais-roguelike

anvil.png: *daneeklu-farming
crops.png: *daneeklu-farming
fence.png: *daneeklu-farming

sign.png:
    derived-from: lpc-signpost

fountain.png:
    derived-from: lpc-water-fountain

door.png:
    derived-from: lpc-doors-animated


crystal-ward.png:
    author: Stuart Pernsteiner
    derived-from: daneeklu-farming-tilesets, gervais-roguelike-tiles

interior-wall.png: &interior-wall
    author: Stuart Pernsteiner
    derived-from: lpc-base-tiles
brick-wall.png: *interior-wall

tree.png: &tree
    author: Anonymous, Stuart Pernsteiner
    derived-from: lpc-base-tiles
tree.xcf: *tree
tree-planemap.png: *tree

tree-trunk.png: *lpc-base
tree-top-round.png: *lpc-base
tree-shadow-round.png: *lpc-base
tree-stump.png: *nilsson-lpc

statue.png:
    title: Pony Statue
    author: Fernando Ariel dos Santos Alves
    license: CC-BY 4.0

torch.*:
    author: Stuart Pernsteiner
    attribution:
        Daniel Eddeland's fence post, plus the top of the torch from Curt's animated water and fire.
    derived-from: lpc-water-and-fire, daneeklu-farming-tilesets

wood_wall.png: &wood-wall
    author: Nonnykins
    attribution: Wood texture based on Nemisys's LPC Signpost
    derived-from: lpc-signpost
wood_wall-planemap.png: *wood-wall

stone-wall.png: &stone-wall
    title: Stone Brick Wall
    author: Nonnykins, Stuart Pernsteiner
stone-wall.xcf: *stone-wall
stone-wall-planemap.png: *stone-wall

ruined-wall.png:
    title: Ruined Stone Brick Wall
    author: Nonnykins

cottage-wall.png: &cottage-wall
    title: Cottage Wall
    author: Nonnykins
cottage-wall-planemap.png: *cottage-wall

door-rough.png:
    title: Rough Wooden Door
    author: Nonnykins
    attribution: Wood texture based on Nemisys's LPC Signpost
    derived-from: lpc-signpost

pillar.png: &pillar
    title: Pillars
    author: Nonnykins
    attribution: Wood texture based on Nemisys's LPC Signpost
    derived-from: lpc-signpost
pillar-planemap.png: *pillar

cave-door.png: &cave-door
    title: Cave Door Animation
    author: Anonymous
    derived-from: lpc-base-tiles
cave-doorway-keyhole.png: *cave-door
cave-doorway-plain.png: *cave-door

gem-puzzle-parts.png:
    title: Gem Puzzle Parts
    author: Stuart Pernsteiner
    attribution: >
        Stone block is the base from the LPC cup.  Gems are based on the
        crystals and coins from the roguelike tiles by David E. Gervais.
    derived-from: lpc-base-tiles, gervais-roguelike-tiles
