witch-hat-?.*:
    title: Witch's Hat
    author: Fernando Ariel dos Santos Alves
    license: CC-BY 4.0

explorer-hat.*:
    title: Explorer Hat
    author: Nonnykins

party-hat*.*:
    title: Party Hat
    author: Stuart Pernsteiner
